version: "3"
services:
  api:
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    links:
      - "db"
    environment:
      NODE_ENV: "production"
      DATABASE: "mongodb://db/place"
      PORT: 3000
      ONLY_LISTEN_LOCAL: "false"


  db:
    image: mongo
    restart: always
    volumes:
      - "./mongo-volume:/data/db"
    ports:
      - "27017:27017"
